import './globals.css';
import { Fira_Mono } from 'next/font/google';
import { Manrope } from 'next/font/google';
import ClientRootWrapper from './components/ClientRootWrapper';



export const metadata = {
  title: "Potify",
  description: "Generated by create Potify app",
};

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '600', '700'],
  display: 'swap',
});

const firaMono = Fira_Mono({
  variable: '--font-fira-mono',
  subsets: ['latin', 'cyrillic'],
  weight: ['400'],
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={`${manrope.variable} ${firaMono.variable} font-sans`}>
        <ClientRootWrapper>{children}</ClientRootWrapper>
      </body>
    </html>
  );
}
